# Generated by Django 4.0.6 on 2022-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslatorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inglizcha', models.CharField(max_length=150, verbose_name='Inglizcha')),
                ('uzbekcha', models.CharField(max_length=160, verbose_name="O'zbekcha")),
            ],
        ),
    ]
